language: swift
osx_image: xcode12.5
script: 
 - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace 'Gaming.xcworkspace' -scheme 'Gaming' -destination 'platform=iOS Simulator,OS=14.5,name=iPhone 11 Pro' | xcpretty

